// Generated by CoffeeScript 1.9.3
var map, util;

map = new google.maps.Map(document.getElementById('map'), {
  center: {
    lat: -34.397,
    lng: 150.644
  },
  zoom: 8
});

util = new MapUtill({
  map: map
});

google.maps.event.addListenerOnce(map, 'idle', function() {
  var $el, bounds, change, dimentions, p1, p2, rectangle;
  p1 = new google.maps.LatLng(45.5983128, 8.8172776);
  p2 = new google.maps.LatLng(45.4355729, 9.169236);
  bounds = new google.maps.LatLngBounds(p1, p2);
  rectangle = new google.maps.Rectangle({
    bounds: bounds,
    map: map,
    strokeColor: 'red',
    fillOpacity: 0
  });
  dimentions = ['left', 'right', 'bottom', 'top'];
  $el = {};
  dimentions.map(function(item) {
    return $el[item] = {
      panel: $(".panel__" + item),
      input: $("#input-" + item)
    };
  });
  change = function() {
    var offset, val;
    offset = {};
    val = function($el) {
      return parseInt($el.val(), 10) || 0;
    };
    dimentions.map(function(dim) {
      var v;
      v = offset[dim] = val($el[dim].input);
      if (dim === 'left' || dim === 'right') {
        $el[dim].panel.width(v);
      } else {
        $el[dim].panel.height(v);
      }
      return $el[dim].input.next().text(v + " px");
    });
    return util.fitBounds(bounds, offset);
  };
  change();
  return $('input').on('input', change);
});

//# sourceMappingURL=main.js.map
